INSERT INTO trinities (id, beginning, middle, end_col, color, sort_order) VALUES (1, 'Governing', 'Operating', 'Dissolution', '#af574f', 1);
INSERT INTO trinities (id, beginning, middle, end_col, color, sort_order) VALUES (2, 'Brahma', 'Vishnu', 'Shankara', '#af644f', 2);
INSERT INTO trinities (id, beginning, middle, end_col, color, sort_order) VALUES (3, 'Saraswati', 'Laxmi', 'Parvati', '#af724f', 3);
INSERT INTO trinities (id, beginning, middle, end_col, color, sort_order) VALUES (4, 'Yesterday', 'Today', 'Tomorrow', '#af804f', 4);
INSERT INTO trinities (id, beginning, middle, end_col, color, sort_order) VALUES (5, 'Morning', 'Afternoon', 'Night', '#af8e4f', 5);
INSERT INTO trinities (id, beginning, middle, end_col, color, sort_order) VALUES (6, 'Present', 'Futur', 'Past', '#af9c4f', 6);
INSERT INTO trinities (id, beginning, middle, end_col, color, sort_order) VALUES (7, 'Body', 'Mind', 'Soul', '#afaa4f', 7);
INSERT INTO trinities (id, beginning, middle, end_col, color, sort_order) VALUES (8, 'Physical', 'Emotional', 'Spiritual', '#a7af4f', 8);
INSERT INTO trinities (id, beginning, middle, end_col, color, sort_order) VALUES (9, 'Father', 'Son', 'Holy Spirit', '#9aaf4f', 9);
INSERT INTO trinities (id, beginning, middle, end_col, color, sort_order) VALUES (10, 'Sato', 'Rajas', 'Tamo', '#8caf4f', 10);
INSERT INTO trinities (id, beginning, middle, end_col, color, sort_order) VALUES (11, 'Sthula', 'Sukshma', 'Nirakari', '#7eaf4f', 11);
INSERT INTO trinities (id, beginning, middle, end_col, color, sort_order) VALUES (12, 'Budhi', 'Manas', 'Sanskara', '#70af4f', 12);
INSERT INTO trinities (id, beginning, middle, end_col, color, sort_order) VALUES (13, 'Intellect', 'Intelligence', 'Wisdom', '#62af4f', 13);
INSERT INTO trinities (id, beginning, middle, end_col, color, sort_order) VALUES (14, 'Yantra', 'Tantra', 'Mantra', '#54af4f', 14);
INSERT INTO trinities (id, beginning, middle, end_col, color, sort_order) VALUES (15, 'Love', 'Happiness', 'Health', '#4faf57', 15);
INSERT INTO trinities (id, beginning, middle, end_col, color, sort_order) VALUES (16, 'Thoughts', 'Knowledge', 'Impact', '#4faf64', 16);
INSERT INTO trinities (id, beginning, middle, end_col, color, sort_order) VALUES (17, 'F1', 'F2', 'F3', '#4faf72', 17);
INSERT INTO trinities (id, beginning, middle, end_col, color, sort_order) VALUES (18, 'Illusion', 'Delusion', 'Visualization', '#4faf80', 18);
INSERT INTO trinities (id, beginning, middle, end_col, color, sort_order) VALUES (19, 'Teacher', 'Guru', 'Satguru', '#4faf8e', 19);
INSERT INTO trinities (id, beginning, middle, end_col, color, sort_order) VALUES (20, 'Atom', 'Electron', 'Proton', '#4faf9c', 20);
INSERT INTO trinities (id, beginning, middle, end_col, color, sort_order) VALUES (21, 'Corporal World', 'Subtle World', 'Incorporal World', '#4fafaa', 21);
INSERT INTO trinities (id, beginning, middle, end_col, color, sort_order) VALUES (22, 'Dhata', 'Vidhata', 'Bhagya Vidhata', '#4fa7af', 22);
INSERT INTO trinities (id, beginning, middle, end_col, color, sort_order) VALUES (23, 'Doctor', 'Nurse', 'Surgeon', '#4f9aaf', 23);
INSERT INTO trinities (id, beginning, middle, end_col, color, sort_order) VALUES (24, 'Akarma', 'Sukarma', 'Vikarma', '#4f8caf', 24);
INSERT INTO trinities (id, beginning, middle, end_col, color, sort_order) VALUES (25, 'True Words', 'Necessary Words', 'Helpful Words', '#4f7eaf', 25);
INSERT INTO trinities (id, beginning, middle, end_col, color, sort_order) VALUES (26, 'Birth', 'Choice', 'Death', '#4f70af', 26);
INSERT INTO trinities (id, beginning, middle, end_col, color, sort_order) VALUES (27, 'Masculine', 'Feminine', 'Trans Gender', '#4f62af', 27);
INSERT INTO trinities (id, beginning, middle, end_col, color, sort_order) VALUES (28, 'Physical Healing', 'Mental Healing', 'Spiritual Healing', '#4f54af', 28);
INSERT INTO trinities (id, beginning, middle, end_col, color, sort_order) VALUES (29, 'Silence', 'Sweet Silence', 'Dead Silence', '#574faf', 29);
INSERT INTO trinities (id, beginning, middle, end_col, color, sort_order) VALUES (30, 'Vatha Dosha', 'Kapha Dosha', 'Pitta Dosha', '#644faf', 30);
INSERT INTO trinities (id, beginning, middle, end_col, color, sort_order) VALUES (31, 'Atma Vidhya', 'Maha Vidhya', 'Sri Vidhya', '#724faf', 31);
INSERT INTO trinities (id, beginning, middle, end_col, color, sort_order) VALUES (32, 'Testimonial', 'Inferred', 'Experiential', '#804faf', 32);
INSERT INTO trinities (id, beginning, middle, end_col, color, sort_order) VALUES (33, 'Sthula Sharir', 'Sukshma Sharir', 'Karan Sharir', '#8e4faf', 33);
INSERT INTO trinities (id, beginning, middle, end_col, color, sort_order) VALUES (34, 'Day', 'Year', 'Kalpa', '#9c4faf', 34);
INSERT INTO trinities (id, beginning, middle, end_col, color, sort_order) VALUES (35, 'Left Eye', 'Right Eye', 'Middle Eye', '#aa4faf', 35);
INSERT INTO trinities (id, beginning, middle, end_col, color, sort_order) VALUES (36, 'Water', 'Trees', 'Earth', '#af4fa7', 36);
INSERT INTO trinities (id, beginning, middle, end_col, color, sort_order) VALUES (37, 'Advaitha', 'Dwaitha', 'Vishishtadvaita', '#af4f9a', 37);
INSERT INTO trinities (id, beginning, middle, end_col, color, sort_order) VALUES (38, 'Ida', 'Pingala', 'Sushamna', '#af4f8c', 38);
INSERT INTO trinities (id, beginning, middle, end_col, color, sort_order) VALUES (39, 'Yajur Veda', 'Rigveda', 'Sama Veda', '#af4f7e', 39);
INSERT INTO trinities (id, beginning, middle, end_col, color, sort_order) VALUES (40, 'Seeker', 'Meditation', 'Bramh', '#af4f70', 40);
INSERT INTO trinities (id, beginning, middle, end_col, color, sort_order) VALUES (41, 'Knower', 'Knowing', 'Known', '#af4f62', 41);
INSERT INTO trinities (id, beginning, middle, end_col, color, sort_order) VALUES (42, 'Nirvikari', 'Nirahankari', 'Nirayani', '#af4f54', 42);
